### ISSUE TITLE
RAM Rastergrösse und Position anpassen

### ISSUE THREAD

**Issue by TheJP** [TheJP/stebs#10]
* Ort überdenken, bin mir noch nicht schlüssig RAM hat aber zu viel Platz nötig
* Das Feld soll 16 x 16 gross dargestellt sein

**Comment by TheJP** [comment]
Wir werden einen Vorschlag ausarbeiten und möchten diesen dann gerne mit dir am Dienstag 24.11.2015 in der Projektwoche besprechen. (Ein Meeting an diesem Tag ist ja bereits vorgesehen.)

**Comment by the-s-a-m** [comment]
RAM eventuell in Devices

**Comment by the-s-a-m** [comment]
RAM muss kopierbar sein 16x16 nur Inhalt und Space separiert

**Comment by TheJP** [comment]
Wird durch @the-s-a-m in Rastergrösse 16 x 16 umgesetzt und nach Devices verschoben.
