### ISSUE TITLE
Aktive Zeile hervorheben

### ISSUE THREAD

**Issue by TheJP** [TheJP/stebs#34]
Sichtbar machen der Zeile des Quellcodes, die vor Ausführung steht.

**Comment by TheJP** [comment]
Das Feature ist bereits eingeplant und es werden auch bereits die mapping Informationen (RAM Adresse zu Zeilen Nummer) an den Client (Browser) übertragen.

**Comment by the-s-a-m** [comment]
Closed by #34c402b
