### ISSUE TITLE
Pluginintegration: Fehlendes, erklärtes Beispiel im Projektbericht

### ISSUE THREAD

**Issue by AceVanCleef** [TheJP/stebs#62]
Salut zusammen

Ich studiere an der FHNW im fünften Semester und arbeite gerade an einem IP5 Projekt, bei welchem wir Plugins für Webstebs entwickeln sollen.

Mit Hilfe eurer Dokumentation, die wir von Herr Müller erhielten, gelang es mir bis anhin, ein neues Plugin im Client anzuzeigen (html/css - Repräsentation). Jedoch verstehe ich noch nicht, wie man bei z.B.

MOV AL,03
MOV BL,02
ADD AL,BL
OUT 00

...den Wert von AL im Plugin entgegen nimmt. Zwar sieht man im [TrafficLightPlugin](https://github.com/TheJP/stebs/blob/master/TrafficLight/TrafficLightPlugin.cs) zwischen Zeile 75 bis 87 einen Codeausschnitt, der ganz klar jQuery enthält. Doch ist dieses Codesnippet zu wenig aufschlussreich.

Wie kann ich:
- bei OUT xx den Wert aus dem AL-Register im Plugin empfangen?
- bei IN xx den Wert im Plugin ins Backend schicken?

Liebe Grüsse, 
Stefan

**Comment by TheJP** [comment]
Hallo @AceVanCleef

Sorry für die späte Antwort, ich war für 2 Monate nicht an einem PC und bin erst seit Sonntagmorgen wieder zurück. Ich hoffe ihr habt herausgefunden wie die Schnittstelle funktioniert.

# Der Vollständigkeit halber
Als erster Info würde ich [IDevice.cs](https://github.com/TheJP/stebs/blob/031763646262f967585eb28409d87d6baa618271/ProcessorSimulation/Device/IDevice.cs) ansehen. Dies ist der Einstiegspunkt zur Pluginentwicklung.

## Wie kann ich bei OUT xx den Wert aus dem AL-Register im Plugin empfangen?
Die Instruktionen werden auf dem Server simuliert. Wird eine `OUT xx` Instruktion ausgeführt, ruft die Simulation die Methode `void Input(byte input)` deiner IDevice Implementation auf.

Im TrafficLight Beispiel wird der Input lokal gespeichert und danach ein Update an den Client gesendet: [TrafficLightDevice.cs](https://github.com/TheJP/stebs/031763646262f967585eb28409d87d6baa618271/master/TrafficLight/TrafficLightDevice.cs)

## Wie kann ich bei IN xx den Wert im Plugin ins Backend schicken?
Der Wert sollte beim Simulieren der Instruktion bereits im Backend sein. Wird eine `IN xx ` Instruktion ausgeführt, ruft die Simulation die Methode `byte Output()` deiner IDevice Implementation auf. Der erhaltene Wert wird dann in das AL-Register geschrieben.


## Nachtrag: Backend <-> Client Kommunikation für Plugins
Um Userinputs aus dem Client zu erhalten und um den Client mit neuen Daten zu aktualisieren existieren ebenfalls Schnittstellen.

Mit `Stebs.updateDevice({slot}, 'some string');` (javascript) kann im Client ein String an das Backend gesendet werden. Dies ruft die Methode `void Update(string input)` deiner IDevice Implementation auf. (Ein Beispiel kann im InterruptDevice Plugin gesehen werden.)

Aus einer Subklasse von DefaultDevice kann mit `View.UpdateView(new SomeUpdate(input))` (C#) ein Update vom Backend an den Client gesendet werden. Das Update kann ein beliebiges [POCO](https://stackoverflow.com/questions/250001/poco-definition) sein, welches von IDeviceUpdate erbt. Im Client können auf solche Updates mit einem solchen Aufruf durch eine _javascript callback function_ gehört werden: `Stebs.registerDevice({slot}, function(data){ ... })`. (Ein Beispiel kann im TrafficLightDevice Plugin gesehen werden.)
