### ISSUE TITLE
Icon Reihenfolge

### ISSUE THREAD

**Issue by TheJP** [TheJP/stebs#7]
Reihenfolge der Icons überdenken. Mit Senkrechtstrichen in Gruppen unterteilen.

**Comment by TheJP** [comment]
Das Design von Stebs erhält zu einem späteren Zeitpunkt einen Feinschliff. Zurzeit ist es unsere Priorität Funktionalität umzusetzen. Viele Anpassungswünsche ergeben sich bei diesem Feinschliff wahrscheinlich von selbst.

**Comment by the-s-a-m** [comment]
closed by commit  83470f5
